package rules
import com.owt.drools.entity.Order


rule "A"
   when
      $u : Order(fs >= 90)
   then
       System.out.println("你的分数为"+$u.getFs() +"评级为A级");
       $u.setNews("你的分数为"+$u.getFs() +"评级为A级");
   end

rule "B"
   when
      $u : Order(fs >= 80 && fs < 90)
    then
      System.out.println("你的分数为"+$u.getFs() +"评级为B级");
      $u.setNews("你的分数为"+$u.getFs() +"评级为B级");
    end

rule "C"
   when
      $u : Order(fs >= 60 && fs < 80)
   then
      System.out.println("你的分数为"+$u.getFs() +"评级为C级");
      $u.setNews("你的分数为"+$u.getFs() +"评级为C级");
    end

rule "D"
   when
      $u : Order(fs < 60)
   then
      System.out.println("你的分数为"+$u.getFs() +"评级为D级");
      $u.setNews("你的分数为"+$u.getFs() +"评级为D级");
    end